# Generated by Django 5.1.15 on 2026-07-01 12:26

import django.utils.timezone
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelTrackerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=120)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('delta', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('icon_label', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'verbose_name': 'AI model tracker item',
                'verbose_name_plural': 'AI model tracker items',
                'ordering': ['sort_order', 'id'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='AppEcosystemCTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField(blank=True)),
                ('cta_label', models.CharField(default='Explore the app', max_length=60)),
                ('cta_url', models.CharField(blank=True, help_text='Internal path or full URL.', max_length=255)),
                ('app_store_url', models.URLField(blank=True)),
                ('google_play_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'app/ecosystem CTA',
                'verbose_name_plural': 'app/ecosystem CTAs',
                'ordering': ['-updated_at', 'id'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='LiveSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, help_text='Optional internal path or full URL.', max_length=255)),
            ],
            options={
                'verbose_name': 'live signal',
                'verbose_name_plural': 'live signals',
                'ordering': ['sort_order', 'id'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='MarketWatchlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=16)),
                ('company_name', models.CharField(max_length=120)),
                ('value', models.CharField(blank=True, max_length=40)),
                ('delta', models.CharField(blank=True, max_length=24)),
                ('delta_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], default='neutral', max_length=16)),
                ('sector', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'market/watchlist item',
                'verbose_name_plural': 'market/watchlist items',
                'ordering': ['sort_order', 'id'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='NorthSignalBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField(blank=True)),
                ('cta_label', models.CharField(default='Preview brief', max_length=60)),
                ('cta_url', models.CharField(blank=True, help_text='Internal path or full URL.', max_length=255)),
                ('email_placeholder', models.CharField(default='Enter your email', max_length=80)),
                ('trust_text', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'North Signal brief',
                'verbose_name_plural': 'North Signal briefs',
                'ordering': ['-updated_at', 'id'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ResearchBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('document_type', models.CharField(choices=[('report', 'Report'), ('briefing', 'Briefing'), ('research', 'Research'), ('pdf', 'PDF'), ('link', 'Link')], default='briefing', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='research_briefs/')),
                ('external_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'research brief',
                'verbose_name_plural': 'research briefs',
                'ordering': ['sort_order', 'id'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='StatusMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=40)),
                ('sublabel', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('neutral', 'Neutral'), ('active', 'Active'), ('bullish', 'Bullish'), ('warning', 'Warning')], default='neutral', max_length=16)),
                ('sparkline', models.CharField(blank=True, help_text='Optional short value or visual hint, for example +2.1%.', max_length=40)),
            ],
            options={
                'verbose_name': 'status metric',
                'verbose_name_plural': 'status metrics',
                'ordering': ['sort_order', 'id'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='TrendingTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('signal_count', models.PositiveIntegerField(default=0)),
                ('trend_label', models.CharField(choices=[('rising', 'Rising'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='rising', max_length=16)),
                ('url', models.CharField(blank=True, help_text='Optional internal path or full URL.', max_length=255)),
            ],
            options={
                'verbose_name': 'trending topic',
                'verbose_name_plural': 'trending topics',
                'ordering': ['sort_order', 'id'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
    ]
