# Generated by Django 5.1.15 on 2026-07-01 17:53

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='article_context_label',
            field=models.CharField(blank=True, help_text='Context label such as AI Infrastructure, Policy & Regulation, or Market Intelligence.', max_length=120),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='confidence_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('verified', 'Verified')], max_length=16),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='impact_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Editorial impact label shown in article badges and intelligence cards.', max_length=16),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='impact_model_metric_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='impact_model_metric_value',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='impact_model_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='impact_model_secondary_metric',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='impact_model_source',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='impact_model_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='intelligence_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='pull_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='pull_quote_attribution',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='pull_quote_source_label',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='signal_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Numeric signal score, for example 91.8.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='source_confidence',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('verified', 'Verified')], max_length=16),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='time_sensitivity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=16),
        ),
        migrations.CreateModel(
            name='ArticleKeyTakeaway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('text', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_takeaways', to='news.articlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleRelatedSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('fallback_title', models.CharField(blank=True, help_text='Used when no Live Signal is selected.', max_length=160)),
                ('fallback_url', models.CharField(blank=True, help_text='Optional internal path or full URL for the fallback title.', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_related_signals', to='news.articlepage')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='intelligence.livesignal')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleSignalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=80)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_tags', to='news.articlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
