# Generated by Django 5.1.15 on 2026-07-02 01:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_intelligencesectionpage_sectionlivesignal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='ai_fact_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='ai_generated_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='ai_researched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='editorial_priority',
            field=models.PositiveSmallIntegerField(default=50, help_text='0-100 priority. Higher values are promoted first in editorial surfaces.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='editorial_reviewer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='editorial_status',
            field=models.CharField(choices=[('idea', 'Idea'), ('assigned', 'Assigned'), ('ai_drafted', 'AI drafted'), ('in_review', 'In review'), ('verified', 'Verified'), ('ready_to_publish', 'Ready to publish'), ('published', 'Published'), ('archived', 'Archived')], default='idea', max_length=24),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='final_editorial_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='headline_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='human_review_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='human_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='image_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='include_in_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='internal_editorial_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='legal_risk_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='mobile_preview_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='production_agent_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='promote_in_section',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='promote_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='seo_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='show_as_breaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='show_in_live_signals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='source_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='source_status',
            field=models.CharField(choices=[('single_source', 'Single source'), ('multi_source', 'Multi source'), ('official_source', 'Official source'), ('primary_document', 'Primary document'), ('wire_verified', 'Wire verified'), ('internal_analysis', 'Internal analysis')], default='single_source', max_length=24),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='sources_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='urgency_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('developing', 'Developing'), ('urgent', 'Urgent'), ('breaking', 'Breaking')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('source_checked', 'Source checked'), ('cross_checked', 'Cross checked'), ('legally_sensitive', 'Legally sensitive'), ('verified', 'Verified'), ('disputed', 'Disputed')], default='unverified', max_length=24),
        ),
        migrations.CreateModel(
            name='ArticleSourceReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=180)),
                ('url', models.URLField(max_length=500)),
                ('source_type', models.CharField(choices=[('official', 'Official'), ('company', 'Company'), ('government', 'Government'), ('wire', 'Wire'), ('research', 'Research'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=16)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('verified', 'Verified')], default='medium', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='news.articlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
